using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class audioOrientacion : MonoBehaviour
{
    public List<AudioClip> audiosOrientacion = new List<AudioClip>();
    public AudioClip audioO0;
    public AudioClip audioO1;
    public AudioClip audioO2;
    public AudioClip audioO3;
    public AudioClip audioO4;
    public AudioClip audioO5;
    public AudioClip audioO6;
    public AudioClip audioO7;
    public AudioClip audioO8;
    public AudioClip audioO9;
    public AudioClip audioO10;
    public AudioClip audioO11;
    public AudioClip audioO12;
    public AudioClip audioO13;
    public AudioClip audioO14;
    public AudioClip audioO15;
    public AudioClip audioO16;
    public AudioClip audioO17;
    public AudioClip audioO18;
    public AudioClip audioO19;
    public AudioClip audioO20;
    public AudioClip audioO21;
    public AudioClip audioO22;
    public AudioClip audioO23;
    public AudioClip audioO24;
    public AudioClip audioO25;
    public AudioClip audioO26;
    public AudioClip audioO27;
    public AudioClip audioO28;
    public AudioClip audioO29;
    public AudioClip audioO30;
    public AudioClip audioO31;
    public AudioClip audioO32;
    public AudioClip audioO33;
    public AudioClip audioO34;
    public AudioClip audioO35;
    public AudioClip audioO36;
    public AudioClip audioO37;
    public AudioClip audioO38;
    public AudioClip audioO39;
    public AudioClip audioO40;
    public AudioClip audioO41;
    public AudioClip audioO42;
    public AudioClip audioO43;
    public AudioClip audioO44;
    public AudioClip audioO45;
    public AudioClip audioO46;
    public AudioClip audioO47;
    public AudioClip audioO48;


    private void Awake()
    {
        audiosOrientacion.Add(audioO0);
        audiosOrientacion.Add(audioO1);
        audiosOrientacion.Add(audioO2);
        audiosOrientacion.Add(audioO3);
        audiosOrientacion.Add(audioO4);
        audiosOrientacion.Add(audioO5);
        audiosOrientacion.Add(audioO6);
        audiosOrientacion.Add(audioO7);
        audiosOrientacion.Add(audioO8);
        audiosOrientacion.Add(audioO9);
        audiosOrientacion.Add(audioO10);
        audiosOrientacion.Add(audioO11);
        audiosOrientacion.Add(audioO12);
        audiosOrientacion.Add(audioO13);
        audiosOrientacion.Add(audioO14);
        audiosOrientacion.Add(audioO15);
        audiosOrientacion.Add(audioO16);
        audiosOrientacion.Add(audioO17);
        audiosOrientacion.Add(audioO18);
        audiosOrientacion.Add(audioO19);
        audiosOrientacion.Add(audioO20);
        audiosOrientacion.Add(audioO21);
        audiosOrientacion.Add(audioO22);
        audiosOrientacion.Add(audioO23);
        audiosOrientacion.Add(audioO24);
        audiosOrientacion.Add(audioO25);
        audiosOrientacion.Add(audioO26);
        audiosOrientacion.Add(audioO27);
        audiosOrientacion.Add(audioO28);
        audiosOrientacion.Add(audioO29);
        audiosOrientacion.Add(audioO30);
        audiosOrientacion.Add(audioO31);
        audiosOrientacion.Add(audioO32);
        audiosOrientacion.Add(audioO33);
        audiosOrientacion.Add(audioO34);
        audiosOrientacion.Add(audioO35);
        audiosOrientacion.Add(audioO36);
        audiosOrientacion.Add(audioO37);
        audiosOrientacion.Add(audioO38);
        audiosOrientacion.Add(audioO39);
        audiosOrientacion.Add(audioO40);
        audiosOrientacion.Add(audioO41);
        audiosOrientacion.Add(audioO42);
        audiosOrientacion.Add(audioO43);
        audiosOrientacion.Add(audioO44);
        audiosOrientacion.Add(audioO45);
        audiosOrientacion.Add(audioO46);
        audiosOrientacion.Add(audioO47);
        audiosOrientacion.Add(audioO48);

    }
}
